const USERNAME_MINLEN = 6;
const USERNAME_MAXLEN = 32;
const PASSWORD_MINLEN = 6;
const PASSWORD_MAXLEN = 32;

const MESSAGE_TYPE = {
  initial: 0,
  normal: 1,
};

module.exports = {
  USERNAME_MINLEN,
  USERNAME_MAXLEN,
  PASSWORD_MINLEN,
  PASSWORD_MAXLEN,
  MESSAGE_TYPE,
}