const USERNAME_LEN_LOWERLIMIT = 6;
const USERNAME_LEN_UPPERLIMIT = 32;
const PASSWORD_LEN_LOWERLIMIT = 6;
const PASSWORD_LEN_UPPERLIMIT = 32;

module.exports = {
  USERNAME_LEN_LOWERLIMIT,
  USERNAME_LEN_UPPERLIMIT,
  PASSWORD_LEN_LOWERLIMIT,
  PASSWORD_LEN_UPPERLIMIT,
}